/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SetupInfoIndexRouteImport } from './routes/setup-info/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as GuestTermsOfServiceIndexRouteImport } from './routes/_guest/terms-of-service/index'
import { Route as GuestPrivacyPolicyIndexRouteImport } from './routes/_guest/privacy-policy/index'
import { Route as GuestPricingIndexRouteImport } from './routes/_guest/pricing/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedInvoicesNewIndexRouteImport } from './routes/_authenticated/invoices/new/index'
import { Route as AuthenticatedInvoicesIdIndexRouteImport } from './routes/_authenticated/invoices/$id/index'
import { Route as AuthenticatedInvoicesIdEditIndexRouteImport } from './routes/_authenticated/invoices/$id/edit/index'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupInfoIndexRoute = SetupInfoIndexRouteImport.update({
  id: '/setup-info/',
  path: '/setup-info/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GuestTermsOfServiceIndexRoute =
  GuestTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => GuestRoute,
  } as any)
const GuestPrivacyPolicyIndexRoute = GuestPrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestPricingIndexRoute = GuestPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesNewIndexRoute =
  AuthenticatedInvoicesNewIndexRouteImport.update({
    id: '/invoices/new/',
    path: '/invoices/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIdIndexRoute =
  AuthenticatedInvoicesIdIndexRouteImport.update({
    id: '/invoices/$id/',
    path: '/invoices/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIdEditIndexRoute =
  AuthenticatedInvoicesIdEditIndexRouteImport.update({
    id: '/invoices/$id/edit/',
    path: '/invoices/$id/edit/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/login/': typeof LoginIndexRoute
  '/setup-info/': typeof SetupInfoIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/pricing/': typeof GuestPricingIndexRoute
  '/privacy-policy/': typeof GuestPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof GuestTermsOfServiceIndexRoute
  '/invoices/$id/': typeof AuthenticatedInvoicesIdIndexRoute
  '/invoices/new/': typeof AuthenticatedInvoicesNewIndexRoute
  '/invoices/$id/edit/': typeof AuthenticatedInvoicesIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/login': typeof LoginIndexRoute
  '/setup-info': typeof SetupInfoIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/pricing': typeof GuestPricingIndexRoute
  '/privacy-policy': typeof GuestPrivacyPolicyIndexRoute
  '/terms-of-service': typeof GuestTermsOfServiceIndexRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdIndexRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_guest/': typeof GuestIndexRoute
  '/login/': typeof LoginIndexRoute
  '/setup-info/': typeof SetupInfoIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_guest/pricing/': typeof GuestPricingIndexRoute
  '/_guest/privacy-policy/': typeof GuestPrivacyPolicyIndexRoute
  '/_guest/terms-of-service/': typeof GuestTermsOfServiceIndexRoute
  '/_authenticated/invoices/$id/': typeof AuthenticatedInvoicesIdIndexRoute
  '/_authenticated/invoices/new/': typeof AuthenticatedInvoicesNewIndexRoute
  '/_authenticated/invoices/$id/edit/': typeof AuthenticatedInvoicesIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/login/'
    | '/setup-info/'
    | '/clients/'
    | '/invoices/'
    | '/pricing/'
    | '/privacy-policy/'
    | '/terms-of-service/'
    | '/invoices/$id/'
    | '/invoices/new/'
    | '/invoices/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/setup-info'
    | '/clients'
    | '/invoices'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_guest/'
    | '/login/'
    | '/setup-info/'
    | '/_authenticated/clients/'
    | '/_authenticated/invoices/'
    | '/_guest/pricing/'
    | '/_guest/privacy-policy/'
    | '/_guest/terms-of-service/'
    | '/_authenticated/invoices/$id/'
    | '/_authenticated/invoices/new/'
    | '/_authenticated/invoices/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SetupInfoIndexRoute: typeof SetupInfoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-info/': {
      id: '/setup-info/'
      path: '/setup-info'
      fullPath: '/setup-info/'
      preLoaderRoute: typeof SetupInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_guest/terms-of-service/': {
      id: '/_guest/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof GuestTermsOfServiceIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/privacy-policy/': {
      id: '/_guest/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof GuestPrivacyPolicyIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/pricing/': {
      id: '/_guest/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof GuestPricingIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/new/': {
      id: '/_authenticated/invoices/new/'
      path: '/invoices/new'
      fullPath: '/invoices/new/'
      preLoaderRoute: typeof AuthenticatedInvoicesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$id/': {
      id: '/_authenticated/invoices/$id/'
      path: '/invoices/$id'
      fullPath: '/invoices/$id/'
      preLoaderRoute: typeof AuthenticatedInvoicesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$id/edit/': {
      id: '/_authenticated/invoices/$id/edit/'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit/'
      preLoaderRoute: typeof AuthenticatedInvoicesIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedInvoicesIdIndexRoute: typeof AuthenticatedInvoicesIdIndexRoute
  AuthenticatedInvoicesNewIndexRoute: typeof AuthenticatedInvoicesNewIndexRoute
  AuthenticatedInvoicesIdEditIndexRoute: typeof AuthenticatedInvoicesIdEditIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedInvoicesIdIndexRoute: AuthenticatedInvoicesIdIndexRoute,
  AuthenticatedInvoicesNewIndexRoute: AuthenticatedInvoicesNewIndexRoute,
  AuthenticatedInvoicesIdEditIndexRoute: AuthenticatedInvoicesIdEditIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestIndexRoute: typeof GuestIndexRoute
  GuestPricingIndexRoute: typeof GuestPricingIndexRoute
  GuestPrivacyPolicyIndexRoute: typeof GuestPrivacyPolicyIndexRoute
  GuestTermsOfServiceIndexRoute: typeof GuestTermsOfServiceIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestIndexRoute: GuestIndexRoute,
  GuestPricingIndexRoute: GuestPricingIndexRoute,
  GuestPrivacyPolicyIndexRoute: GuestPrivacyPolicyIndexRoute,
  GuestTermsOfServiceIndexRoute: GuestTermsOfServiceIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SetupInfoIndexRoute: SetupInfoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
