import { forwardRef } from "react";
import type { Invoice, Client } from "@/lib/types";
import { format } from "date-fns";
import { formatCurrency } from "@/lib/utils";
import { calculateSubTotal, calculateTaxAmount, calculateTotalAmount } from "@/lib/utils";

type InvoicePDFProps = {
  invoice: Invoice;
  client: Client | null;
  bussinessname?: string;
};

export const DefaultInvoiceTemplate = forwardRef<HTMLDivElement, InvoicePDFProps>(
  ({ invoice, client, bussinessname }, ref) => (
    <main ref={ref}>
      <div className="">
        <div className="">
          <p className="">{bussinessname}</p>
          <div className="">
            <p className="">{invoice.id}</p>
            <p>Issue Date: {format(new Date(invoice.issueDate), "MMM d, yyyy")}</p>
            <p>Due Date: {format(new Date(invoice.dueDate), "MMM d, yyyy")}</p>
          </div>
        </div>

        <div className="">
          <p className="">Bill To</p>
          {client && (
            <>
              <p className="">{client.name}</p>
              <p className="">{client.email}</p>
              {client.phone && <p className="">{client.phone}</p>}
              {client.address && <p className="">{client.address}</p>}
              <p className="">
                {" "}
                {client.city}, {client.country}{" "}
              </p>
            </>
          )}
        </div>

        <div className="">
          <div className="">
            <p className="">Description</p>
            <p className="">Qty</p>
            <p className="">Unit Price</p>
            <p className="">Total</p>
          </div>
          {invoice.items.map((item, index) => (
            <div key={index} className="">
              <p className="">{item.description}</p>
              <p className="">{item.quantity}</p>
              <p className="">{formatCurrency(item.unitPrice)}</p>
              <p className="">{formatCurrency(item.quantity * item.unitPrice)}</p>
            </div>
          ))}
        </div>

        <div className="">
          <div className="">
            <p className="">Subtotal</p>
            <p>{formatCurrency(calculateSubTotal(invoice.items))}</p>
          </div>
          <div className="">
            <p className="">Tax ({invoice.taxRate}%)</p>
            <p>{formatCurrency(calculateTaxAmount(invoice.items, invoice.taxRate))}</p>
          </div>
          <div className="">
            <p className="">Total</p>
            <p>{formatCurrency(calculateTotalAmount(invoice.items, invoice.taxRate))}</p>
          </div>
        </div>

        {invoice.notes && (
          <div className="">
            <p className="">Notes</p>
            <p>{invoice.notes}</p>
          </div>
        )}

        <p className="">Thank you for your business! | Generated by IHOD</p>
      </div>
    </main>
  ),
);
