import { forwardRef } from "react";
import type { Invoice, Client } from "@/lib/types";
import { format } from "date-fns";
import { formatCurrency } from "@/lib/utils";
import { calculateSubTotal, calculateTaxAmount, calculateTotalAmount } from "@/lib/utils";

type InvoicePDFProps = {
  invoice: Invoice;
  client: Client | null;
  bussinessname?: string;
};

export const DefaultInvoiceTemplate = forwardRef<HTMLDivElement, InvoicePDFProps>(
  ({ invoice, client, bussinessname }, ref) => (
    <main ref={ref} className="bg-white w-[210mm] min-h-[295mm] mx-auto p-[15mm] text-gray-800 print:p-[15mm]">
      <div className="h-full flex flex-col justify-between">
        {/* Top Content */}
        <div className="space-y-8">
          {/* Header */}
          <div className="flex justify-between items-start border-b pb-6">
            <div>
              <p className="text-3xl font-bold">{bussinessname}</p>
            </div>
            <div className="text-right text-sm space-y-1">
              <p className="font-semibold text-lg">Invoice #{invoice.id}</p>
              <p>Issue: {format(new Date(invoice.issueDate), "MMM d, yyyy")}</p>
              <p>Due: {format(new Date(invoice.dueDate), "MMM d, yyyy")}</p>
            </div>
          </div>

          {/* Bill To */}
          <div className="bg-gray-50 p-6 rounded-xl">
            <p className="text-xs font-semibold uppercase text-gray-500 mb-2">Bill To</p>
            {client && (
              <div className="space-y-1 text-sm">
                <p className="font-medium text-base">{client.name}</p>
                <p>{client.email}</p>
                {client.phone && <p>{client.phone}</p>}
                {client.address && <p>{client.address}</p>}
                <p>
                  {client.city}, {client.country}
                </p>
              </div>
            )}
          </div>

          {/* Table */}
          <div className="w-full">
            <div className="grid grid-cols-4 bg-gray-100 text-gray-600 text-sm font-semibold py-3 px-4 rounded-t-lg">
              <p>Description</p>
              <p className="text-center">Qty</p>
              <p className="text-right">Unit</p>
              <p className="text-right">Total</p>
            </div>

            {invoice.items.map((item, index) => (
              <div key={index} className="grid grid-cols-4 py-3 border-b text-sm">
                <p>{item.description}</p>
                <p className="text-center">{item.quantity}</p>
                <p className="text-right">{formatCurrency(item.unitPrice)}</p>
                <p className="text-right font-medium">{formatCurrency(item.quantity * item.unitPrice)}</p>
              </div>
            ))}
          </div>

          {/* Totals */}
          <div className="flex justify-end">
            <div className="w-[300px] space-y-2 text-sm">
              <div className="flex justify-between">
                <p>Subtotal</p>
                <p>{formatCurrency(calculateSubTotal(invoice.items))}</p>
              </div>
              <div className="flex justify-between">
                <p>Tax ({invoice.taxRate}%)</p>
                <p>{formatCurrency(calculateTaxAmount(invoice.items, invoice.taxRate))}</p>
              </div>
              <div className="flex justify-between font-bold text-lg border-t pt-2">
                <p>Total</p>
                <p>{formatCurrency(calculateTotalAmount(invoice.items, invoice.taxRate))}</p>
              </div>
            </div>
          </div>

          {/* Notes */}
          {invoice.notes && (
            <div>
              <p className="text-xs font-semibold uppercase text-gray-500 mb-1">Notes</p>
              <p className="text-sm">{invoice.notes}</p>
            </div>
          )}
        </div>

        {/* Bottom Section (Signatures + Footer) */}
        <div className="pt-10">
          <p className="text-xs font-semibold uppercase text-gray-500 mb-1">Signatures</p>
          <div className="grid grid-cols-2 gap-12 mb-8">
            <div className="text-center">
              <div className="border-t mt-16 pt-2 text-sm">{bussinessname}</div>
            </div>
            <div className="text-center">
              <div className="border-t mt-16 pt-2 text-sm">{client?.name}</div>
            </div>
          </div>

          <p className="text-center text-xs text-gray-400">Thank you for your business! | Generated by IHOD</p>
        </div>
      </div>
    </main>
  ),
);
