import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { Client, Invoice } from "@/lib/types";
import { format } from "date-fns";
import { calculateSubTotal, calculateTaxAmount, calculateTotalAmount } from "@/lib/utils";
import { formatCurrency } from "@/lib/utils";
import { defaultStyles as styles } from "./styles/default";

type InvoicePDFProps = {
  invoice: Invoice;
  client: Client | null;
};

export function InvoicePDF({ invoice, client }: InvoicePDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.logo}>IHOD</Text>
          <View style={styles.invoiceInfo}>
            <Text style={styles.invoiceNumber}>{invoice.id}</Text>
            <Text>Issue Date: {format(new Date(invoice.issueDate), "MMM d, yyyy")}</Text>
            <Text>Due Date: {format(new Date(invoice.dueDate), "MMM d, yyyy")}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Bill To</Text>
          {client && (
            <>
              <Text style={styles.clientName}>{client.name}</Text>
              <Text>{client.email}</Text>
              {client.phone && <Text>{client.phone}</Text>}
              {client.address && <Text>{client.address}</Text>}
              <Text>
                {client.city}, {client.country}
              </Text>
            </>
          )}
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Description</Text>
            <Text style={styles.col2}>Qty</Text>
            <Text style={styles.col3}>Unit Price</Text>
            <Text style={styles.col4}>Total</Text>
          </View>
          {invoice.items.map((item, index) => (
            <View key={index} style={styles.tableRow}>
              <Text style={styles.col1}>{item.description}</Text>
              <Text style={styles.col2}>{item.quantity}</Text>
              <Text style={styles.col3}>{formatCurrency(item.unitPrice)}</Text>
              <Text style={styles.col4}>{formatCurrency(item.quantity * item.unitPrice)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.totals}>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Subtotal</Text>
            <Text>{formatCurrency(calculateSubTotal(invoice.items))}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Tax ({invoice.taxRate}%)</Text>
            <Text>{formatCurrency(calculateTaxAmount(invoice.items, invoice.taxRate))}</Text>
          </View>
          <View style={styles.grandTotal}>
            <Text style={styles.grandTotalLabel}>Total</Text>
            <Text style={styles.grandTotalValue}>
              {formatCurrency(calculateTotalAmount(invoice.items, invoice.taxRate))}
            </Text>
          </View>
        </View>

        {invoice.notes && (
          <View style={styles.notes}>
            <Text style={styles.notesTitle}>Notes</Text>
            <Text>{invoice.notes}</Text>
          </View>
        )}

        <Text style={styles.footer}>Thank you for your business! | Generated by IHOD</Text>
      </Page>
    </Document>
  );
}
