import { forwardRef } from "react";
import type { Invoice, Client } from "@/lib/types";
import { defaultStyles as styles } from "./styles/default";
import { format } from "date-fns";
import { formatCurrency } from "@/lib/utils";
import { calculateSubTotal, calculateTaxAmount, calculateTotalAmount } from "@/lib/utils";

type InvoicePDFProps = {
  invoice: Invoice;
  client: Client | null;
};

export const InvoicePrint = forwardRef<HTMLDivElement, InvoicePDFProps>(({ invoice, client }, ref) => (
  <div ref={ref}>
    <div style={styles.page}>
      <div style={styles.header}>
        <p style={styles.logo}>IHOD</p>
        <div style={styles.invoiceInfo}>
          <p style={styles.invoiceNumber}>{invoice.id}</p>
          <p>Issue Date: {format(new Date(invoice.issueDate), "MMM d, yyyy")}</p>
          <p>Due Date: {format(new Date(invoice.dueDate), "MMM d, yyyy")}</p>
        </div>
      </div>

      <div style={styles.section}>
        <p style={styles.sectionTitle}>Bill To</p>
        {client && (
          <>
            <p style={styles.clientName}>{client.name}</p>
            <p>{client.email}</p>
            {client.phone && <p>{client.phone}</p>}
            {client.address && <p>{client.address}</p>}
            <p>
              {" "}
              {client.city}, {client.country}{" "}
            </p>
          </>
        )}
      </div>

      <div style={styles.table}>
        <div style={styles.tableHeader}>
          <p style={styles.col1}>Description</p>
          <p style={styles.col2}>Qty</p>
          <p style={styles.col3}>Unit Price</p>
          <p style={styles.col4}>Total</p>
        </div>
        {invoice.items.map((item, index) => (
          <div key={index} style={styles.tableRow}>
            <p style={styles.col1}>{item.description}</p>
            <p style={styles.col2}>{item.quantity}</p>
            <p style={styles.col3}>{formatCurrency(item.unitPrice)}</p>
            <p style={styles.col4}>{formatCurrency(item.quantity * item.unitPrice)}</p>
          </div>
        ))}
      </div>

      <div style={styles.totals}>
        <div style={styles.totalRow}>
          <p style={styles.totalLabel}>Subtotal</p>
          <p>{formatCurrency(calculateSubTotal(invoice.items))}</p>
        </div>
        <div style={styles.totalRow}>
          <p style={styles.totalLabel}>Tax ({invoice.taxRate}%)</p>
          <p>{formatCurrency(calculateTaxAmount(invoice.items, invoice.taxRate))}</p>
        </div>
        <div style={styles.grandTotal}>
          <p style={styles.grandTotalLabel}>Total</p>
          <p style={styles.grandTotalValue}>{formatCurrency(calculateTotalAmount(invoice.items, invoice.taxRate))}</p>
        </div>
      </div>

      {invoice.notes && (
        <div style={styles.notes}>
          <p style={styles.notesTitle}>Notes</p>
          <p>{invoice.notes}</p>
        </div>
      )}

      <p style={styles.footer}>Thank you for your business! | Generated by IHOD</p>
    </div>
  </div>
));
